- Cargo.toml
- README.md
Does not effectively change the code base.
nu-ansi-term can now be used without being in lockstep with
nushell/nushell
> Carve out new release version

- README.md
- src/display.rs
- src/lib.rs
All other identifiers use stricter Pascal case (as specified by Rust's style guide)
in `nu-ansi-term` compared to base `rust-ansi-term`
Confirmed with GitHub code search that this change should not cause
major breakage
> Rename ANSIByteStrings constructor for consistency

- Cargo.toml
- README.md
- src/display.rs
- src/util.rs
The `Deref` implementation for `AnsiGenericString` and its derived type aliases probably violates the tacit definition of the `Deref` trait:
https://doc.rust-lang.org/std/ops/trait.Deref.html
As the type aliases implement `Display` for the actual styling logic they get a blanket `impl ToString for T: Display + ?Sized`
This has the nasty consequence that while you would expect that `fn foo(input: AsRef<str>)` would get the same input from `let styled: AnsiGenericString<_> = ...` for both `foo(styled)` and `foo(styled.to_string())` this doesn't hold.
Thus the lint <https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_to_owned> will change the actual behavior and remove styling as the underlying string gets presented via `Deref`.
This change removes the `Deref` …
> Remove `impl Deref` for `AnsiGenericString`

- src/display.rs
Hello, I've been in process of converting https://github.com/ogham/exa from `rust-ansi-term` to `nu-ansi-term` and there is one api that exa needs that was lost during the refactoring from rust-ansi-term to nu-ansi-term.
`exa` needs the underlying raw string to calculate widths, previously this api was present in a form, where AnsiString could be dereferenced into `Cow<'a, str>`, directly and the to str, which was then used.
This adds the minimal required code, it just returns `&str` which is the minimum needed.
I tried to workaround this with some other api but could not found any in `nu-ansi-term` and `to_string` would require allocation which seemed unnecessary as the underlying view can be returned directly.
> Allow dereferencing AnsiString as underlying string

- Cargo.toml
- src/rgb.rs
This removes the `overload` dependency by implementing the operators for the `Rgb` struct manually.
The `overload` macro is a bit opaque about what it generates without looking into the documentation. The generate code is fairly simple and therefore I think it's reasonable to maintain the implementation here.
> Implement the provided operators for `Rgb` manually

- Cargo.toml
- src/lib.rs
- src/util.rs
- src/windows.rs
Closes issue #14
How I tested:
```
cargo test --all-features
cargo fmt
cargo clippy --all-features
```
The clippy warning seems to be unrelated, but I've also fixed it since it fails the CI
And then run examples
https://www.yogile.com/alxq57uebw6/21t/share/?vsc=e105adfdf
I've added ``nu_ansi_term::enable_ansi_support().unwrap();`` line a first line for the example ``main`` function as it was not called by examples. I am on Win11
> Replace winapi crate with windows crate

- .github/workflows/ci.yml
The `actions-rs/*` actions are replaced with `dtolnay/rust-toolchain` and plain cargo commands.
> Replace unmaintained/outdated GitHub Actions

- Cargo.toml
- src/windows.rs
The `windows-sys` crate is only 2.5MB, compared to 11.5MB for the `windows` crate.
> Use the `windows-sys` crate

- .github/workflows/ci.yml
- examples/256_colors.rs
- examples/basic_colors.rs
- examples/gradient_colors.rs
- examples/rgb_colors.rs
GitHub Actions log supports ansi colors. Let's show them off.
> Enable ansi support for examples under windows

- Cargo.toml
All other crates from Nushell organization seem to already use this Rust edition. Just update this crate to align the usage of it.
> Rust Edition 2021

- Cargo.toml
clippy respects the rust version set in the package metadata and wouldn't break the build job for newer rust features.
`#[derive(Derive)]` on enums was stabilized with [rust 1.62](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1620-2022-06-30)
- #29
> Set MSRV to 1.62.0 in package metadata

- src/ansi.rs
- src/display.rs
- src/gradient.rs
- src/rgb.rs
- src/style.rs
Constify some functions, in order to use them in const context for other crates.
> Add const on some functions

- CHANGELOG.md
Get the changelog up-to-date (also important points for the release notes)
> Update changelog to reflect planned 0.47 release

- Cargo.toml
- README.md
Will be used starting with `reedline` 0.17 and `nu` 0.77.
> Bump version for `0.47` release.

- Cargo.toml
- src/debug.rs
- src/style.rs
Just a quick work on unit tests. I removed the crate `regex`, since we only used 1% of what we can achieve through a regex, and IMO, we can simply do it without this dependency.
This MR should be looked commit per commit.
> Unit tests update

- src/ansi.rs
A really quick MR to fix a bad doc test.
> Quick fix around doc tests regarding Color::prefix().

- README.md
- examples/basic_colors.rs
- src/ansi.rs
- src/style.rs
Hi,
gnu coreutils are are in parts resetting styles everytime they are applied. 
To make this available in uucoreutils (the rust drop in replacement for gnu core utils) I added a chainable style called "resetted" which will print the reset style before the actual string. 
[Related PR](https://github.com/uutils/coreutils/pull/4867)
```rust
test!(bold:                  Style::new().bold();               "hi" => "\x1B[1mhi\x1B[0m");
test!(bold_with_reset:       Style::new().resetted().bold();    "hi" => "\x1B[0m\x1B[1mhi\x1B[0m");
test!(bold_with_reset_2:     Style::new().bold().resetted();    "hi" => "\x1B[0m\x1B[1mhi\x1B[0m");
```
Please see the code and I hope this feature can make it.
> Add resetted styling

- src/ansi.rs
- src/difference.rs
- src/display.rs
- src/style.rs
Add support for producing colorized/stylized hyperlinks, among a selection of other OS Control (OSC) codes such as setting the window title, application/window icon, and notifying the terminal about the  current working directory. The main goal is to satisfy #6 while also supporting a few other very common OSC codes.
There has already been some discussion and a change proposed for handling hyperlinks in the dormant rust-ansi-term repo: (See: https://github.com/ogham/rust-ansi-term/pull/61) The above proposed change breaks the Copy trait for Style and would require changing downstream projects that rely on it.
These features aren't really about styling text so much as adding more information for the terminal emulator to present to the user either outside of the typical area for rendered …
> Add support for hyperlinks and other OSC codes

- Cargo.toml
This readds the patch versions in the cargo version specifiers to ensure
that we include a tested working version. In theory the could have been
breakage with one of the included patch versions of crates we depend on
so it is best practice to supply a full version specifier. Cargo will
automatically pull in a higher version when running `cargo update` or
building this library with another crate that requires a higher version.
See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio
This reverts commit 313eac446c27b30dc12013692d770d37cd38522f.
> Revert removal of the patch versions

- .github/workflows/ci.yml
- examples/hyperlink.rs
- examples/may_sleep/mod.rs
- examples/title.rs
- src/ansi.rs
- src/difference.rs
- src/display.rs
- src/style.rs
- tests/style.rs
Fixes #46 by moving OSControl out of Style and into AnsiGenericString
> Fix Re-enabling manual Style creation

- examples/hyperlink.rs
- src/display.rs
The API for modifying a string to contain a hyperlink used in #47
behaves different than most of our `Style`-driven APIs that basically
all work through method chaining.
As an alternative I propose we change the signature to take the
`AnsiGenericString` by value and modify it in place. This feels more
expressive for quickly building out a styled string with a link.
One downside compared to a modifying setter API is that it takes a
more tokens to do conditional modification with an `if` expression.
cc @fdncred, @mhelsley
> Use chaining for `AnsiGenericString::hyperlink`

- src/ansi.rs
- src/style.rs
- tests/style.rs
As the behavior is probably a bit unclear and everybody constructing or
destructuring it by hand will now have to take this field into account
we should be as explicit as possible. @fdncred 's suggestion was
`prefix_with_reset`.
I also tried to be even more detailed in the fields docstring for
anybody interacting it after `0.47.0`. @alexkunde check me if I am wrong
here.
> Make `Style.with_reset` more explicit as `prefix_with_reset`

- Cargo.toml
- README.md
Should include the more friendly API breakage from #47
Still a breaking change compared to 0.47 based on #40
> Bump version for 0.49 release

- src/ansi.rs
Fixes:
https://github.com/sharkdp/lscolors/issues/77
> gnu_legacy: with GNU, write foreground first, else background first.

- src/rgb.rs
The import triggers `clippy::legacy_numeric_constants`.
> Remove unused import
